{note;RegEx Vars}
{set;argCount;{if;{args};{math;{length;{replace;{replace;{args};\s;¬};[^|]}}+1};0}}
{set;regex.args.third;(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?$)}
{set;regex.args.fourth;(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?$)}
{set;regex.args.fifth;(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?$)}
{set;regex.args.sixth;(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?$)}
{set;regex.args.seventh;(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?$)}
{set;regex.args.eighth;(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?$)}
{set;regex.args.ninth;(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?)(?:\s?)(?:\|)(?:\s?)(.*?$)}


{if;{and;
  {if;{args};!==;;true};
  {if;{args};!==;help;true}
};==;true;

	{if;{and;
		{if;{get;argCount};>=;3;true};
		{if;{get;argCount};<=;9;true}
	};==;true;
	
		{note;Title + 2 options}
		{if;{get;argCount};===;3;

			{set;title;{find;{args};{get;regex.args.third};1}}
			{set;arg1;{find;{args};{get;regex.args.third};2}}
			{set;arg2;{find;{args};{get;regex.args.third};3}}

			{a!ae;--title="{get;title}";--description=":one:  {get;arg1}\n\n:two:  {get;arg2}";--footer="Asked by {user.nickname}";--timestamp="true"}
				
			{set;messageId;{channel.lastMessageID}}
			{message.react;one;{get;messageId}}
			{message.react;two;{get;messageId}}
		}

		{note;Title + 3 options}
		{if;{get;argCount};===;4;
		
			{set;title;{find;{args};{get;regex.args.fourth};1}}
			{set;arg1;{find;{args};{get;regex.args.fourth};2}}
			{set;arg2;{find;{args};{get;regex.args.fourth};3}}
			{set;arg3;{find;{args};{get;regex.args.fourth};4}}
			
			{a!ae;--title="{get;title}";--description=":one:  {get;arg1}\n\n:two:  {get;arg2}\n\n:three:  {get;arg3}";--footer="Asked by {user.nickname}";--timestamp="true"}
				
			{set;messageId;{channel.lastMessageID}}
			{message.react;one;{get;messageId}}
			{message.react;two;{get;messageId}}
			{message.react;three;{get;messageId}}
		}

		{note;Title + 4 options}
		{if;{get;argCount};===;5;
			
			{set;title;{find;{args};{get;regex.args.fifth};1}}
			{set;arg1;{find;{args};{get;regex.args.fifth};2}}
			{set;arg2;{find;{args};{get;regex.args.fifth};3}}
			{set;arg3;{find;{args};{get;regex.args.fifth};4}}
			{set;arg4;{find;{args};{get;regex.args.fifth};5}}
			
			{a!ae;--title="{get;title}";--description=":one:  {get;arg1}\n\n:two:  {get;arg2}\n\n:three:  {get;arg3}\n\n:four:  {get;arg4}";--footer="Asked by {user.nickname}";--timestamp="true"}
				
			{set;messageId;{channel.lastMessageID}}
			{message.react;one;{get;messageId}}
			{message.react;two;{get;messageId}}
			{message.react;three;{get;messageId}}
			{message.react;four;{get;messageId}}
		}
			
		{note;Title + 5 options}
		{if;{get;argCount};===;6;
			
			{set;title;{find;{args};{get;regex.args.sixth};1}}
			{set;arg1;{find;{args};{get;regex.args.sixth};2}}
			{set;arg2;{find;{args};{get;regex.args.sixth};3}}
			{set;arg3;{find;{args};{get;regex.args.sixth};4}}
			{set;arg4;{find;{args};{get;regex.args.sixth};5}}
			{set;arg5;{find;{args};{get;regex.args.sixth};6}}
			
			{a!ae;--title="{get;title}";--description=":one:  {get;arg1}\n\n:two:  {get;arg2}\n\n:three:  {get;arg3}\n\n:four:  {get;arg4}\n\n:five:  {get;arg5}";--footer="Asked by {user.nickname}";--timestamp="true"}
				
			{set;messageId;{channel.lastMessageID}}
			{message.react;one;{get;messageId}}
			{message.react;two;{get;messageId}}
			{message.react;three;{get;messageId}}
			{message.react;four;{get;messageId}}
			{message.react;five;{get;messageId}}
		}
			
		{note;Title + 6 options}
		{if;{get;argCount};===;7;
			
			{set;title;{find;{args};{get;regex.args.seventh};1}}
			{set;arg1;{find;{args};{get;regex.args.seventh};2}}
			{set;arg2;{find;{args};{get;regex.args.seventh};3}}
			{set;arg3;{find;{args};{get;regex.args.seventh};4}}
			{set;arg4;{find;{args};{get;regex.args.seventh};5}}
			{set;arg5;{find;{args};{get;regex.args.seventh};6}}
			{set;arg6;{find;{args};{get;regex.args.seventh};7}}
			
			{a!ae;--title="{get;title}";--description=":one:  {get;arg1}\n\n:two:  {get;arg2}\n\n:three:  {get;arg3}\n\n:four:  {get;arg4}\n\n:five:  {get;arg5}\n\n:six:  {get;arg6}";--footer="Asked by {user.nickname}";--timestamp="true"}
				
			{set;messageId;{channel.lastMessageID}}
			{message.react;one;{get;messageId}}
			{message.react;two;{get;messageId}}
			{message.react;three;{get;messageId}}
			{message.react;four;{get;messageId}}
			{message.react;five;{get;messageId}}
			{message.react;six;{get;messageId}}
		}
			
		{note;Title + 7 options}
		{if;{get;argCount};===;8;
			
			{set;title;{find;{args};{get;regex.args.eighth};1}}
			{set;arg1;{find;{args};{get;regex.args.eighth};2}}
			{set;arg2;{find;{args};{get;regex.args.eighth};3}}
			{set;arg3;{find;{args};{get;regex.args.eighth};4}}
			{set;arg4;{find;{args};{get;regex.args.eighth};5}}
			{set;arg5;{find;{args};{get;regex.args.eighth};6}}
			{set;arg6;{find;{args};{get;regex.args.eighth};7}}
			{set;arg7;{find;{args};{get;regex.args.eighth};8}}
			
			{a!ae;--title="{get;title}";--description=":one:  {get;arg1}\n\n:two:  {get;arg2}\n\n:three:  {get;arg3}\n\n:four:  {get;arg4}\n\n:five:  {get;arg5}\n\n:six:  {get;arg6}\n\n:seven:  {get;arg7}";--footer="Asked by {user.nickname}";--timestamp="true"}
				
			{set;messageId;{channel.lastMessageID}}
			{message.react;one;{get;messageId}}
			{message.react;two;{get;messageId}}
			{message.react;three;{get;messageId}}
			{message.react;four;{get;messageId}}
			{message.react;five;{get;messageId}}
			{message.react;six;{get;messageId}}
			{message.react;seven;{get;messageId}}
		}
			
		{note;Title + 8 options}
		{if;{get;argCount};===;9;
			
			{set;title;{find;{args};{get;regex.args.ninth};1}}
			{set;arg1;{find;{args};{get;regex.args.ninth};2}}
			{set;arg2;{find;{args};{get;regex.args.ninth};3}}
			{set;arg3;{find;{args};{get;regex.args.ninth};4}}
			{set;arg4;{find;{args};{get;regex.args.ninth};5}}
			{set;arg5;{find;{args};{get;regex.args.ninth};6}}
			{set;arg6;{find;{args};{get;regex.args.ninth};7}}
			{set;arg7;{find;{args};{get;regex.args.ninth};8}}
			{set;arg8;{find;{args};{get;regex.args.ninth};9}}
			
			{a!ae;--title="{get;title}";--description=":one:  {get;arg1}\n\n:two:  {get;arg2}\n\n:three:  {get;arg3}\n\n:four:  {get;arg4}\n\n:five:  {get;arg5}\n\n:six:  {get;arg6}\n\n:seven:  {get;arg7}\n\n:eight:  {get;arg8}";--footer="Asked by {user.nickname}";--timestamp="true"}
				
			{set;messageId;{channel.lastMessageID}}
			{message.react;one;{get;messageId}}
			{message.react;two;{get;messageId}}
			{message.react;three;{get;messageId}}
			{message.react;four;{get;messageId}}
			{message.react;five;{get;messageId}}
			{message.react;six;{get;messageId}}
			{message.react;seven;{get;messageId}}
			{message.react;eight;{get;messageId}}
		}
		
		;
		
		{if;{get;argCount};<;3;
			{channel.send;Error: You must have at least 2 options.}
		}
		
		{if;{get;argCount};>;9;
			{channel.send;Error: You cannot have more than 8 poll options.}
		}
		
	}

;{a!ae;--field1name="Command Usage";--field1value="`!poll` - Show the help dialog\n`!poll <title>|<option1>|<option2>[|<option3>...<option8>]`";--field2name="Example Usage";--field2value="`!poll What is my name?|Stasis Bot|Atlas|Ship Bot`";--title="**Poll Help**";--footer="Note: Min options: 2, Max options: 8";--description="The poll command allows you to create a react-based poll."}}